name: Scheduled Node.js Job

on:
  schedule:
    - cron: "* * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run Node.js script
        run: |
          npm install  # Install dependencies if needed
          node test.js  # Replace with your actual script name
