name: Scheduled Node.js Job

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Run Node.js script
        run: |
          npm install  # Install dependencies if needed
          node test.js  # Replace with your actual script name
        env:
          TELEGRAM_HTTP_TOKEN: ${{ secrets.TELEGRAM_HTTP_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_CHAT_ID_ADMIN: ${{ secrets.TELEGRAM_CHAT_ID_ADMIN }}
